/**
 * Regenerate `drizzle/seed-d1.sql` dari database lokal yang sudah di-seed.
 *
 * File SQL hasil generate memakai `INSERT OR IGNORE` sehingga aman dijalankan
 * berulang kali ke D1 remote tanpa menimpa data yang sudah ada.
 *
 * Jalankan: bun scripts/export-d1-seed.ts
 */
import { Database } from "bun:sqlite";
import { writeFileSync } from "node:fs";

const DB_PATH = "./data/inventory.db";
const OUT_PATH = "./drizzle/seed-d1.sql";

const db = new Database(DB_PATH, { readonly: true });

type Row = Record<string, unknown>;

function q(sql: string): Row[] {
  return db.prepare(sql).all() as Row[];
}

function lit(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Row[], columns?: string[]): string {
  if (rows.length === 0) return "";
  const cols = columns ?? Object.keys(rows[0]);
  const values = rows
    .map((r) => `(${cols.map((c) => lit(r[c])).join(", ")})`)
    .join(",\n");
  return `INSERT OR IGNORE INTO ${table} (${cols.join(", ")}) VALUES\n${values};\n`;
}

/**
 * Backfill kolom harga untuk baris yang sudah ada di D1.
 * `INSERT OR IGNORE` melewati baris lama, tanpa ini `buy_price`/`sell_price`
 * dan harga paket akan tetap kosong di database yang sudah terisi.
 */
function backfill(
  table: string,
  rows: Row[],
  setColumns: string[],
  whereColumns: string[],
  extraWhere?: string
): string {
  if (rows.length === 0) return "";
  const lines = rows.map((r) => {
    const sets = setColumns.map((c) => `${c} = ${lit(r[c])}`).join(", ");
    const wheres = [
      ...whereColumns.map((c) => `${c} = ${lit(r[c])}`),
      ...(extraWhere ? [extraWhere] : []),
    ].join(" AND ");
    return `UPDATE ${table} SET ${sets} WHERE ${wheres};`;
  });
  return lines.join("\n") + "\n";
}

/** Empat paket demo (id persis, bukan pola longgar agar baris uji tidak ikut). */
const DEMO_PACKAGE_IDS = ["pkg-sd1-int", "pkg-sd1-nas", "pkg-sd2-int", "pkg-sd2-nas"];
const DEMO_PACKAGE_ID_SQL = DEMO_PACKAGE_IDS.map((id) => `'${id}'`).join(",");

const out: string[] = [
  "-- Generated by scripts/export-d1-seed.ts. Do not edit by hand.",
  "-- Run: bun run db:d1:seed  (applies drizzle/seed-d1.sql to remote D1)",
  "",
  "-- Cakupan baris demo ditentukan oleh seed resmi: lokasi 'school-%', akun domain",
  "-- sekolah, buku ber-ISBN riil, paket 'pkg-sd%', dan semua baris yang thereof",
  "-- Achieved lewat relasi. Baris hasil pengujian otomatis tidak ikut ekspor.",
  "",
];

/** Buku demo: ISBN riil (bukan prefix test 'ISBN-'). */
const DEMO_BOOKS = `SELECT * FROM books WHERE isbn LIKE '978-%'`;
/** Murid demo: NIS numerik 10 digit (bukan prefix test 'NIS-'). */
const DEMO_STUDENTS = `SELECT * FROM students WHERE nis GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'`;
/** Paket demo. */
const DEMO_PACKAGES = `SELECT * FROM book_packages WHERE id IN (${DEMO_PACKAGE_ID_SQL})`;
/** Order demo: order milik murid demo. */
const DEMO_ORDERS = `SELECT o.* FROM student_book_orders o
  WHERE o.student_id IN (SELECT id FROM students WHERE nis GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')`;
/** PO demo: PO milik supplier demo. */
const DEMO_POS = `SELECT * FROM purchase_orders WHERE supplier_id IN (
    SELECT id FROM suppliers WHERE code IN ('SUP-ERL','SUP-MEN'))`;

out.push(
  "-- 0. Schools (4 Al Wildan campuses + Gudang Logistik)",
  insert(
    "schools",
    q(`SELECT id, name, code, type, address, phone, created_at, updated_at
         FROM schools WHERE id LIKE 'school-%' ORDER BY id`)
  )
);

out.push(
  "-- 1. Staff accounts (central, warehouse, branch admins)",
  insert(
    "users",
    q(`SELECT id, name, email, role, school_id, created_at, updated_at
         FROM users WHERE email LIKE '%@alwildan.sch.id' ORDER BY id`)
  )
);

out.push(
  "-- 2. Master Books (buy_price + sell_price)",
  insert(
    "books",
    q(`SELECT id, isbn, title, author, publisher, category, publish_year,
              price, buy_price, sell_price, created_at, updated_at
         FROM (${DEMO_BOOKS}) ORDER BY id`)
  ),
  "-- 2b. Backfill harga beli/jual untuk buku lama (hanya yang belum terisi)",
  backfill(
    "books",
    q(`SELECT id, buy_price, sell_price FROM (${DEMO_BOOKS}) WHERE sell_price > 0 ORDER BY id`),
    ["buy_price", "sell_price"],
    ["id"],
    "(sell_price IS NULL OR sell_price = 0)"
  )
);

out.push(
  "-- 3. Book Packages (price = SUM(sell_price * qty) of components)",
  insert(
    "book_packages",
    q(`SELECT id, code, name, grade_level, curriculum_type, academic_year,
              price, description, created_at, updated_at
         FROM (${DEMO_PACKAGES}) ORDER BY id`)
  ),
  "-- 3b. Selaraskan harga paket yang sudah ada dengan komponen terkini",
  backfill(
    "book_packages",
    q(`SELECT id, price FROM (${DEMO_PACKAGES}) ORDER BY id`),
    ["price"],
    ["id"]
  )
);

out.push(
  "-- 4. Package BOM Components",
  insert(
    "book_package_items",
    q(`SELECT bpi.id, bpi.package_id, bpi.book_id, bpi.quantity, bpi.created_at
         FROM book_package_items bpi
        WHERE bpi.package_id IN (SELECT id FROM book_packages WHERE id IN (${DEMO_PACKAGE_ID_SQL}))
        ORDER BY bpi.id`)
  )
);

out.push(
  "-- 5. Students",
  insert(
    "students",
    q(`SELECT id, school_id, nis, name, gender, grade_level, curriculum_type,
              academic_year, parent_name, parent_email, parent_phone, status,
              is_scholarship, created_at, updated_at
         FROM (${DEMO_STUDENTS}) ORDER BY id`)
  )
);

out.push(
  "-- 6. Student Book Orders",
  insert(
    "student_book_orders",
    q(`SELECT id, order_number, student_id, school_id, package_id, order_type,
              payment_status, fulfillment_status, total_amount, paid_amount,
              notes, created_at, updated_at
         FROM (${DEMO_ORDERS}) ORDER BY order_number`)
  )
);

out.push(
  "-- 7. Order Payments",
  insert(
    "order_payments",
    q(`SELECT p.id, p.order_id, p.transfer_amount, p.book_allocation_amount,
              p.bank_name, p.reference_number, p.notes, p.created_at
         FROM order_payments p
        WHERE p.order_id IN (SELECT id FROM student_book_orders
                              WHERE student_id IN (SELECT id FROM students WHERE nis GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
        ORDER BY p.id`)
  )
);

out.push(
  "-- 8. Suppliers",
  insert(
    "suppliers",
    q(`SELECT id, code, name, contact_person, email, phone, address, created_at, updated_at
         FROM suppliers WHERE code IN ('SUP-ERL', 'SUP-MEN') ORDER BY id`)
  )
);

out.push(
  "-- 9. Purchase Orders (target = Gudang Logistik, diskon per item)",
  insert(
    "purchase_orders",
    q(`SELECT id, po_number, supplier_id, target_school_id, status, order_date,
              expected_arrival_date, subtotal_gross, discount_total, total_amount,
              notes, created_at, updated_at
         FROM (${DEMO_POS}) ORDER BY po_number`)
  )
);

out.push(
  "-- 10. Purchase Order Items",
  insert(
    "purchase_order_items",
    q(`SELECT i.id, i.purchase_order_id, i.book_id, i.quantity_ordered,
              i.quantity_received, i.unit_price, i.discount_percent, i.created_at
         FROM purchase_order_items i
        WHERE i.purchase_order_id IN (
            SELECT id FROM purchase_orders WHERE supplier_id IN (
                SELECT id FROM suppliers WHERE code IN ('SUP-ERL','SUP-MEN')))
        ORDER BY i.id`)
  )
);

out.push(
  "-- 11. Loose stock (book_items) di lokasi sekolah",
  insert(
    "book_items",
    q(`SELECT bi.id, bi.book_id, bi.current_school_id, bi.barcode, bi.condition,
              bi.status, bi.notes, bi.created_at, bi.updated_at
         FROM book_items bi
        WHERE bi.book_id IN (SELECT id FROM books WHERE isbn LIKE '978-%')
          AND bi.notes = 'Loose stock inventory'
        ORDER BY bi.id`)
  )
);

out.push(
  "-- 12. Ready bundles (package_items)",
  insert(
    "package_items",
    q(`SELECT pi.id, pi.package_id, pi.current_school_id, pi.barcode, pi.status,
              pi.notes, pi.created_at, pi.updated_at
         FROM package_items pi
        WHERE pi.package_id IN (SELECT id FROM book_packages WHERE id IN (${DEMO_PACKAGE_ID_SQL}))
        ORDER BY pi.id`)
  )
);

db.close();
writeFileSync(OUT_PATH, out.filter(Boolean).join("\n"), "utf8");
console.log(`Wrote ${OUT_PATH}`);
